---
- name: Install XServer
  become: true
  package:
    name: "{{ item }}"
  with_items:
    - xserver-xorg
    - xinit

- name: Install a login manager
  become: true
  package:
    name: lightdm

- name: Install a window manager
  become: true
  package:
    name: "{{ item }}"
  with_items:
    - lxde-core
    - lxappearance

- name: Boot into desktop mode
  become: true
  file:
    dest: /etc/systemd/system/default.target
    src: /lib/systemd/system/graphical.target
    state: link

- name: Install Arduino Studio
  package:
    name: arduino
    state: present
