######################################################################
# Install a Desktop environment on the Raspberry by. Connect via VNC.
# This will need the RealVNC VNC Viewer on the Mac:
# `brew cask install vnc-viewer`
######################################################################
---
- name: Install XServer
  become: true
  package:
    name: "{{ item }}"
  with_items:
    - xserver-xorg
    - xinit

- name: Force screen resolution (width)
  become: true
  lineinfile:
    dest: "/boot/config.txt"
    line: "framebuffer_width=1280"
    regexp: '^(#)?framebuffer_width=\d*'

- name: Force screen resolution (height)
  become: true
  lineinfile:
    dest: "/boot/config.txt"
    line: "framebuffer_height=720"
    regexp: '^(#)?framebuffer_height=\d*'

- name: Install a login manager
  become: true
  package:
    name: lightdm

- name: Install a window manager
  become: true
  package:
    name: "{{ item }}"
  with_items:
    - lxde-core
    - lxappearance

- name: Install VNC Server
  become: true
  package:
    name: realvnc-vnc-server
    state: present

- name: Start VNC server
  become: true
  service:
    name: vncserver-x11-serviced
    enabled: true
    state: started

- name: Boot into desktop mode
  become: true
  file:
    dest: /etc/systemd/system/default.target
    src: /lib/systemd/system/graphical.target
    state: link
